### ISSUE TITLE
Package latency regression

### ISSUE THREAD

**Issue by stillyslalom** [stillyslalom/CineFiles.jl#7]
The 'time to first .cine' increased sharply with https://github.com/stillyslalom/CineFiles.jl/commit/373fc336b0ac058e4a65042bd1ae9f339125f307, which uses large static arrays known to be burdensome to the compiler.

**Comment by stillyslalom** [comment]
One possible solution: https://github.com/analytech-solutions/CBinding.jl

**Comment by stillyslalom** [comment]
See also: https://github.com/JuliaIO/HDF5.jl/pull/745

**Comment by james-bird** [comment]
I have made some changes which speed up "time to first .cine". Still not lightning fast, but much better:
https://github.com/stillyslalom/CineFiles.jl/pull/8

**Comment by stillyslalom** [comment]
Closed by https://github.com/stillyslalom/CineFiles.jl/pull/8
